services:
  # redis service
  email-marketing-v2-redis:
    image: 'redis:alpine'
    container_name: sistema-online-email-marketing-v2-redis
    ports:
      - 6381:6379
    volumes:
      - sistema-online-email-marketing-v2-redis:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - sistema-online
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 6144M
        reservations:
          cpus: '1.00'
          memory: 2048M

  # php-fpm service
  email-marketing-v2-php-fpm:
    container_name: sistema-online-email-marketing-v2-php-fpm
    ports:
      - 9002:9000
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: sistema-online-email-marketing-v2-php-fpm
    volumes:
      - ../..:/var/www/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - email-marketing-v2-redis
    networks:
      - sistema-online
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 6144M
        reservations:
          cpus: '1.00'
          memory: 2048M
  
  # nginx service
  email-marketing-v2-nginx:
    image: nginx:latest
    container_name: sistema-online-email-marketing-v2-nginx
    volumes:
      - ../..:/var/www/html:rw
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8083:80"
    depends_on:
      - email-marketing-v2-php-fpm
    networks:
      - sistema-online
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 6144M
        reservations:
          cpus: '1.00'
          memory: 2048M

  # horizon service
  email-marketing-v2-horizon:
    image: sistema-online-email-marketing-v2-php-fpm
    container_name: sistema-online-email-marketing-v2-horizon
    command: php artisan horizon
    volumes:
      - ../..:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - sistema-online
    depends_on:
      - email-marketing-v2-php-fpm
      - email-marketing-v2-redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 6144M
        reservations:
          cpus: '1.00'
          memory: 2048M

  # scheduler service
  email-marketing-v2-scheduler:
    image: sistema-online-email-marketing-v2-php-fpm
    container_name: sistema-online-email-marketing-v2-scheduler
    entrypoint: /bin/sh -c "while :; do php artisan schedule:run; sleep 60; done"
    volumes:
      - ../..:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - sistema-online
    depends_on:
      - email-marketing-v2-php-fpm
      - email-marketing-v2-redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 6144M
        reservations:
          cpus: '1.00'
          memory: 2048M

networks:
  sistema-online:
    driver: bridge
    external: true

volumes:
    sistema-online-email-marketing-v2-redis:
        driver: local
